jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: GitHubPages
    if: github.event_name == 'push'  # Ejecuta deploy solo en push (no en pull requests)
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar permisos para push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Verificar que TOKEN esté configurado
        run: |
          if [ -z "${{ secrets.TOKEN }}" ]; then
            echo "El secreto TOKEN está vacío";
            exit 1;
          else
            echo "El secreto TOKEN está configurado.";
          fi

      - name: Reemplazar el placeholder en index.html
        run: |
          sed -i 's/API_KEY_PLACEHOLDER/${{ secrets.TOKEN }}/g' index.html

      - name: Mostrar primeras 10 líneas de index.html (depuración)
        run: head -n 30 index.html

      - name: Deploy a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./
